config/routes.rb
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do
  root to: "main#index"

  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy", as: :logout

  get "profile", to: "profile#show"
  patch "profile", to: "profile#update"         
  post "profile", to: "profile#update"        
  delete "profile", to: "profile#destroy", as: :delete_user


  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"
  get "password/reset/edit/:token", to: "password_resets#edit", as: :edit_password_reset
  patch "password/reset/edit", to: "password_resets#update"

  # --------------------------------------
  # FACTURAS 
  # --------------------------------------
  
  get "invoices/new", to: "invoices#new", as: :new_invoice

  post "invoices/form", to: "invoices#select_format", as: :select_invoice_format
  get "invoices/form", to: "invoices#new_form", as: :invoice_form

  post "invoices", to: "invoices#create"

  get "invoices/:id", to: "invoices#show", as: :invoice

  get "invoices/:id/export/:format_type", to: "invoices#export", as: :export_invoice
  # ---------------------------------------------------------
  get "about", to: "about#index"

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
  end

 def edit
    @user = User.find_signed!(params[:token], purpose: "password_reset")
  rescue ActiveSupport::MessageVerifier::InvalidSignature
    redirect_to login_path, alert: "Invalid or expired password reset token. Please try again."
  end

 def update
      @user = User.find_signed!(params[:token], purpose: "password_reset")
      if @user.update(password_params)
        redirect_to login_path, notice: "Password has been reset successfully. You can now log in."
      else
        flash.now[:alert] = "Failed to reset password. Please check your inputs."
        render :edit, status: :unprocessable_entity
      end
 end
 
  def create
    @user = User.find_by(email: params[:email])
     if @user.present?
      PasswordMailer.with(user: @user).reset.deliver_now
    else
      render :new, status: :unprocessable_entity
    end
      redirect_to root_path, notice: "Password reset email sent."
  end

  private

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/views/password_resets/edit.html.erb
<h1> Reset your password </h1>

<%= form_with model: @user, url: password_reset_edit_path(token: params[:token]) do |form| %>
    <% if @user.errors.any? %>
        <div class="alert alert-danger">
            <% @user.errors.full_messages.each do |message| %>
                <p><%= message %></p>
            <% end %>
        </div>
    <% end %>
    <div class="mb-3">
        <%= form.label :password, class: "form-label" %>
        <%= form.password_field :password, class: "form-control", autocomplete: "new-password", placeholder: "Enter new password" %>
    </div>
    <div class="mb-3">
        <%= form.label :password_confirmation, class: "form-label" %>
        <%= form.password_field :password_confirmation, class: "form-control", autocomplete: "new-password", placeholder: "Confirm new password" %>
    </div>
  <%= form.submit "Reset password", class: "btn btn-primary" %>
<% end %>

app/views/password_resets/new.html.erb
<h1> Forgot your password? </h1>

<%= form_with url: password_reset_path do |form| %>
  <div class="mb-3">
    <%= form.label :email, class: "form-label" %>
    <%= form.email_field :email, class: "form-control" %>
  </div>
  <%= form.submit "Send reset password mail", class: "btn btn-primary" %>
<% end %>