config/routes.rb
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do
  root to: "main#index"

  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy", as: :logout

  get "profile", to: "profile#show"
  patch "profile", to: "profile#update"         
  post "profile", to: "profile#update"        
  delete "profile", to: "profile#destroy", as: :delete_user


  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"
  get "password/reset/edit/:token", to: "password_resets#edit", as: :edit_password_reset
  patch "password/reset/edit", to: "password_resets#update"

  # --------------------------------------
  # FACTURAS 
  # --------------------------------------
  
  get "invoices/new", to: "invoices#new", as: :new_invoice

  post "invoices/form", to: "invoices#select_format", as: :select_invoice_format
  get "invoices/form", to: "invoices#new_form", as: :invoice_form

  post "invoices", to: "invoices#create"

  get "invoices/:id", to: "invoices#show", as: :invoice

  get "invoices/:id/export/:format_type", to: "invoices#export", as: :export_invoice
  # ---------------------------------------------------------
  get "about", to: "about#index"

end

app/views/shared/_flash_messages.html.erb
<% if flash[:notice].present? %>
  <div class="alert alert-info mt-4" role="alert">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert].present? %>
  <div class="alert alert-danger mt-4" role="alert">
    <%= flash[:alert].inspect %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-primary bg-primary mb-4">
  <div class="container-fluid">
    <%= link_to "Home", root_path, class: "navbar-brand text-white fw-bold" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <%= link_to "About Me", about_path, class: "nav-link text-white" %>
        </li>
      </ul>
      <% unless (controller_name == "session" || controller_name == "registrations") %>
        <% if Current.user %>
          <% @user = Current.user %>
          <% if @user %>
        <span class="navbar-text text-white ms-auto">
          Hi, <%= link_to @user.email.split('@').first, profile_path, class: "text-white text-decoration-none" %>
        </span>
          <% end %>
        <% else %>
          <div class="ms-auto">
            <%= link_to "Sign Up", sign_up_path, class: "btn btn-outline-light me-2" %>
            <%= link_to "Login", login_path, class: "btn btn-outline-light" %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</nav>